import type { Category, Intervention, InterventionType, Synergy } from "./types";

export const INTERVENTIONS: Intervention[] = [
  {
    type: "well",
    name: "Well",
    shortName: "Well",
    icon: "💧",
    category: "water",
    cost: 200_000,
    description:
      "A well does not make tap water. In Thar it taps an aquifer: monsoon rain that seeped deep into rock and sand. That water is often deep, scarce, and brackish.",
    howTo: "Click beside a compound. Then lift (pump), store (tank), and if it is salty, distill or filter.",
    requires: [],
    effects: { waterSource: 6 },
  },
  {
    type: "main_water_line",
    name: "RO drinking kiosk",
    shortName: "RO kiosk",
    icon: "🏪",
    category: "water",
    cost: 80_000,
    description:
      "A communal drinking point. People walk here with cans. Thar homes do not have tap water — this is not a household network.",
    howTo: "Click near a compound. It does not fill wells. Wells still drink the aquifer.",
    requires: [],
    unique: true,
    effects: { waterSource: 8, healthServices: 10 },
  },
  {
    type: "pipeline",
    name: "Well-to-tank pipe",
    shortName: "Pipe",
    icon: "🚰",
    category: "water",
    cost: 180_000,
    description:
      "Moves water you already lifted from the well into a tank. It is not a city main. Thar has no tap-water network.",
    howTo: "Click the well first, then click a ground tank or elevated tank.",
    requires: [{ type: "well", maxDist: 90 }],
    requiresAny: [{ type: "water_tank" }, { type: "elevated_tank" }],
    mode: "connect",
    effects: { waterSource: 6 },
  },
  {
    type: "water_tank",
    name: "Ground tank",
    shortName: "Tank",
    icon: "🛢",
    category: "water",
    cost: 90_000,
    description:
      "The round courtyard tank. You fill it from a well (aquifer water), not from a tap main.",
    howTo: "Click beside a well. Then you can pipe well → tank.",
    requires: [{ type: "well", maxDist: 140 }],
    effects: { storage: 28 },
  },
  {
    type: "rainwater",
    name: "Rainwater harvesting",
    shortName: "Rainwater",
    icon: "🌧",
    category: "water",
    cost: 35_000,
    description:
      "Catches scarce monsoon rain on a roof. That same rain, when it seeps underground, is what recharges the aquifer your well drinks.",
    howTo: "Click a compound courtyard.",
    requires: [],
    effects: { waterSource: 5, storage: 8 },
  },
  {
    type: "solar_still",
    name: "Solar still",
    shortName: "Still",
    icon: "🧪",
    category: "water",
    cost: 20_000,
    description:
      "Student desert still: sun evaporates brackish water under glass. No grid. Slow, but drinkable.",
    howTo: "Click near a well. Feed is brackish groundwater — the still is what makes it safe.",
    requires: [],
    effects: { waterSource: 7, healthServices: 6 },
  },
  {
    type: "elevated_tank",
    name: "Elevated tank",
    shortName: "Tower",
    icon: "🏗️",
    category: "water",
    cost: 45_000,
    description:
      "A gravity tower. Pump once, then water runs downhill to the chaunras — like the student sketches.",
    howTo: "Click beside a well. Useless until something can fill it.",
    requires: [{ type: "well", maxDist: 140 }],
    effects: { storage: 22 },
  },
  {
    type: "house_taps",
    name: "Shared courtyard tap",
    shortName: "Standpipe",
    icon: "🚿",
    category: "water",
    cost: 25_000,
    description:
      "One shared tap in a courtyard, fed from your tank. Not indoor tap water — Thar households do not have that.",
    howTo: "Click a compound after a tank exists. This is a standpipe, not a house connection.",
    requires: [],
    requiresAny: [{ type: "elevated_tank" }, { type: "water_tank" }],
    effects: { waterSource: 12 },
  },
  {
    type: "clay_filter",
    name: "Clay / charcoal filter",
    shortName: "Filter",
    icon: "🏺",
    category: "water",
    cost: 8_000,
    description:
      "Stacked clay pots, charcoal, sand. Bio-filtration with no electricity — the cheap student kit.",
    howTo: "Click a courtyard. Works better next to a still or a tank.",
    requires: [],
    effects: { healthServices: 8, waterSource: 2 },
  },
  {
    type: "demo_house",
    name: "Student demo house",
    shortName: "Demo",
    icon: "🏡",
    category: "human",
    cost: 30_000,
    description:
      "One prototype dwelling: green roof, rooftop solar, rain catch, indoor filter. A teaching house, not a village.",
    howTo: "Click at the edge of a compound. One is enough.",
    requires: [],
    unique: true,
    effects: { waterSource: 4, energy: 5, education: 10, storage: 5 },
  },
  {
    type: "solar_farm",
    name: "Solar farm",
    shortName: "Solar",
    icon: "☀️",
    category: "energy",
    cost: 250_000,
    description: "Village-scale generation. Unlocks pumping, night clinic, and digital work.",
    howTo: "Click open sand away from the thatch — panels need sky.",
    requires: [],
    effects: { energy: 36 },
  },
  {
    type: "solar_pump",
    name: "Solar pump",
    shortName: "Pump",
    icon: "⚙️",
    category: "energy",
    cost: 80_000,
    description: "Lifts water from a nearby well. Needs the well and a solar farm.",
    howTo: "Click next to the well you want to lift from.",
    requires: [
      { type: "well", maxDist: 120 },
      { type: "solar_farm" },
    ],
    effects: { pumping: 24, energy: 2 },
  },
  {
    type: "battery",
    name: "Battery storage",
    shortName: "Battery",
    icon: "🔋",
    category: "energy",
    cost: 70_000,
    description: "Keeps lights and pumps running after sunset.",
    howTo: "Click near the solar farm.",
    requires: [{ type: "solar_farm" }],
    effects: { energy: 10, grid: 8 },
  },
  {
    type: "distribution_line",
    name: "Distribution line",
    shortName: "Grid",
    icon: "⚡",
    category: "energy",
    cost: 80_000,
    description: "Carries electricity from the solar farm into the compounds.",
    howTo: "Click between the solar farm and the chaunras.",
    requires: [{ type: "solar_farm" }],
    effects: { grid: 28 },
  },
  {
    type: "road",
    name: "Bazaar road",
    shortName: "Road",
    icon: "🛣",
    category: "connectivity",
    cost: 150_000,
    description:
      "Packs the goat track to town. Markets, school, and clinic wait on this corridor — it is not a sticker.",
    howTo: "Click the faded track that already runs toward Mithi / Islamkot.",
    requires: [],
    unique: true,
    mode: "unlock",
    effects: { roads: 40 },
  },
  {
    type: "internet_tower",
    name: "Internet tower",
    shortName: "Internet",
    icon: "📡",
    category: "connectivity",
    cost: 80_000,
    description: "Needs power. With a skill center it opens remote work.",
    howTo: "Click a rise near the compounds.",
    requires: [],
    requiresAny: [{ type: "solar_farm" }, { type: "distribution_line" }],
    effects: { digital: 32 },
  },
  {
    type: "market",
    name: "Market",
    shortName: "Market",
    icon: "🏪",
    category: "economy",
    cost: 300_000,
    description: "Better prices only if carts can arrive. Sit it on the bazaar road.",
    howTo: "Click ON the bazaar track, after the road is packed.",
    requires: [{ type: "road" }],
    effects: { markets: 28 },
  },
  {
    type: "livestock_center",
    name: "Livestock center",
    shortName: "Livestock",
    icon: "🐐",
    category: "economy",
    cost: 100_000,
    description: "Pens and vet care. Animals still need the road to reach a buyer.",
    howTo: "Click along the bazaar road.",
    requires: [{ type: "road" }],
    effects: { livestockSupport: 30 },
  },
  {
    type: "processing_unit",
    name: "Small processing unit",
    shortName: "Processing",
    icon: "🏭",
    category: "economy",
    cost: 120_000,
    description: "Adds value to milk, wool, or crafts. Needs a road and electricity.",
    howTo: "Click near the road once solar exists.",
    requires: [{ type: "road" }],
    requiresAny: [{ type: "solar_farm" }, { type: "distribution_line" }],
    effects: { processing: 26 },
  },
  {
    type: "microfinance",
    name: "Microfinance center",
    shortName: "Finance",
    icon: "🏦",
    category: "economy",
    cost: 70_000,
    description: "Savings and small loans. Useful once a market exists to invest in.",
    howTo: "Click near a working market.",
    requires: [{ type: "market" }],
    effects: { finance: 22 },
  },
  {
    type: "school",
    name: "School",
    shortName: "School",
    icon: "🏫",
    category: "human",
    cost: 500_000,
    description: "A classroom. Children only come if the household can spare them.",
    howTo: "Click along the bazaar road.",
    requires: [{ type: "road" }],
    effects: { education: 28 },
  },
  {
    type: "skill_center",
    name: "Skill center",
    shortName: "Skills",
    icon: "👨‍💻",
    category: "human",
    cost: 400_000,
    description: "Training without electricity is a dark room. Needs a road and power.",
    howTo: "Click after solar and the bazaar road exist.",
    requires: [{ type: "road" }],
    requiresAny: [{ type: "solar_farm" }, { type: "distribution_line" }],
    effects: { skills: 26 },
  },
  {
    type: "clinic",
    name: "Clinic",
    shortName: "Clinic",
    icon: "🏥",
    category: "human",
    cost: 450_000,
    description: "Staff and referrals need a road. Clean water makes it usable.",
    howTo: "Click along the road, preferably near a well.",
    requires: [{ type: "road" }],
    effects: { healthServices: 32 },
  },
];

export const SYNERGIES: Synergy[] = [
  {
    id: "piped_well",
    label: "Well water reaches a tank",
    why: "Aquifer water, once lifted, can be stored instead of hauled bucket by bucket.",
    a: { type: "well" },
    b: { type: "pipeline", maxDist: 220 },
    effects: { waterSource: 8 },
  },
  {
    id: "pumped_supply",
    label: "Solar pumping",
    why: "Water can be lifted for livestock and small plots.",
    a: { type: "well" },
    b: { type: "solar_pump", maxDist: 120 },
    effects: { pumping: 12, livestockSupport: 8 },
  },
  {
    id: "stored_supply",
    label: "Courtyard storage",
    why: "The round tank keeps aquifer water through a dry week.",
    a: { type: "well" },
    b: { type: "water_tank", maxDist: 140 },
    effects: { storage: 10 },
  },
  {
    id: "livestock_market",
    label: "Livestock reach a paying market",
    why: "Animals sell at a better price when the road links pen to bazaar.",
    a: { type: "livestock_center" },
    b: { type: "market", maxDist: 260 },
    effects: { markets: 14, livestockSupport: 10 },
  },
  {
    id: "digital_jobs",
    label: "Training meets connectivity",
    why: "Skills become remote work only when the tower and classroom are both live.",
    a: { type: "skill_center" },
    b: { type: "internet_tower" },
    effects: { digital: 18, skills: 10 },
  },
  {
    id: "clinic_water",
    label: "Clean water at the clinic",
    why: "Safe water makes the clinic usable for deliveries and wound care.",
    a: { type: "clinic" },
    b: { type: "well", maxDist: 220 },
    effects: { healthServices: 10 },
  },
  {
    id: "value_add",
    label: "Processing plus livestock",
    why: "Milk and wool leave as products, not raw distress sales.",
    a: { type: "processing_unit" },
    b: { type: "livestock_center" },
    effects: { processing: 12, markets: 8 },
  },
  {
    id: "still_well",
    label: "Brackish well feeds the still",
    why: "Sun turns salty groundwater into a thin stream of drinking water.",
    a: { type: "well" },
    b: { type: "solar_still", maxDist: 140 },
    effects: { waterSource: 10, healthServices: 4 },
  },
  {
    id: "tower_taps",
    label: "Gravity to the courtyard",
    why: "The elevated tank only matters when a courtyard standpipe is fed.",
    a: { type: "elevated_tank" },
    b: { type: "house_taps", maxDist: 220 },
    effects: { waterSource: 14 },
  },
  {
    id: "filter_still",
    label: "Distill, then filter",
    why: "The student off-grid drinking chain: still + clay pots, no electricity.",
    a: { type: "solar_still" },
    b: { type: "clay_filter", maxDist: 160 },
    effects: { healthServices: 8 },
  },
  {
    id: "demo_rain",
    label: "Demo house catches rain",
    why: "The prototype roof is doing the job it was drawn for.",
    a: { type: "demo_house" },
    b: { type: "rainwater", maxDist: 140 },
    effects: { waterSource: 5, education: 4 },
  },
];

export const CATEGORY_META: Record<
  Category,
  { label: string; hint: string }
> = {
  water: { label: "Water", hint: "Aquifer → well → pump / still → tank" },
  energy: { label: "Energy", hint: "Power is a chain, not a sticker" },
  economy: { label: "Economy", hint: "A stall is not a job" },
  human: { label: "People", hint: "A building is not attendance" },
  connectivity: { label: "Links", hint: "Road to town, then internet" },
};

const byType = new Map(INTERVENTIONS.map((item) => [item.type, item]));

export function interventionOf(type: InterventionType) {
  const found = byType.get(type);
  if (!found) {
    throw new Error(`Unknown intervention: ${type}`);
  }
  return found;
}

export const CATEGORY_ORDER: Category[] = [
  "water",
  "energy",
  "economy",
  "human",
  "connectivity",
];
